# Generated by Django 5.1.1 on 2024-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_brand_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.CharField(default="Descripition", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Category", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="Description", max_length=100),
            preserve_default=False,
        ),
    ]
